### ISSUE TITLE
Trying to create a composer project fails because of minimum stability

### ISSUE THREAD

**Issue by MarcusDalgren** [aphiria/app#8]
Following the guide and writing:
`Creating a "aphiria/app" project at "./app"`

Yields the following:
```
[InvalidArgumentException]
Could not find package aphiria/app with stability stable.
```

I had to do this in order to get it to work:
`composer create-project aphiria/app aphiria --prefer-dist -s dev`

All I'm doing is spec:ing my minimum stability to dev and that seems to fix the issue.
Looking forward to trying out the framework!

**Comment by davidbyoung** [comment]
Ah, I missed that.  Fixed.  Thanks for pointing it out!
